build:
  weights:
    # complexity: 2
    # LongParameterList: 1
    # style: 1
    # comments: 1
    detekt-hint: 0

detekt-hint:
  UseCompositionInsteadOfInheritance:
    active: true
    yourUniquePackageName: "io.gitlab.arturbosch.detekt"
    excludes: "**/detekt-rules/**/*Rule.kt"
  LackOfCohesionMethods:
    active: true
    threshold: "0.8"
  InterfaceSegregationPrinciple:
    active: true
  OpenClosedPrinciple:
    active: true

